version: "3.9"

services:
  backend:
    build: .
    container_name: set-plexus-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      - PYTHONUNBUFFERED=1

